apiVersion: v1
kind: Secret
metadata:
  name: appius-secrets
type: Opaque
stringData:
  # Database
  database-url: "postgresql://user:password@postgres:5432/appius?schema=public"
  
  # Redis
  redis-url: "redis://redis:6379"
  
  # JWT
  jwt-secret: "your-super-secret-jwt-key-min-32-chars"
  
  # Stripe
  stripe-secret-key: "sk_test_your_stripe_secret_key"
  stripe-webhook-secret: "whsec_your_stripe_webhook_secret"
  
  # TaxJar
  taxjar-api-key: "your_taxjar_api_key"
  
  # CloudFlare
  cloudflare-api-token: "your_cloudflare_api_token"
  cloudflare-zone-id: "your_cloudflare_zone_id"
  
  # Let's Encrypt
  letsencrypt-email: "admin@appius.com"
  
  # Session
  cookie-secret: "your-super-secret-cookie-key"
  session-secret: "your-super-secret-session-key"
  
  # SMTP (for email notifications)
  smtp-host: "smtp.gmail.com"
  smtp-port: "587"
  smtp-user: "your-email@gmail.com"
  smtp-password: "your-app-specific-password"
  
  # OAuth (for social login)
  google-client-id: "your_google_client_id"
  google-client-secret: "your_google_client_secret"
  github-client-id: "your_github_client_id"
  github-client-secret: "your_github_client_secret"

---
# Note: Create a copy of this file as 'secrets.yaml' with your actual values
# and ensure it's added to .gitignore to keep sensitive data out of version control

# To create the actual secrets in Kubernetes:
# 1. Copy this file to secrets.yaml
# 2. Replace placeholder values with actual secrets
# 3. Run: kubectl apply -f secrets.yaml

# To use these secrets in your deployments:
# env:
#   - name: DATABASE_URL
#     valueFrom:
#       secretKeyRef:
#         name: appius-secrets
#         key: database-url
