output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "eks_cluster_id" {
  description = "The name/id of the EKS cluster"
  value       = module.eks.cluster_id
}

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "eks_node_security_group_id" {
  description = "Security group ID attached to the EKS nodes"
  value       = module.eks.node_security_group_id
}

output "eks_oidc_provider_arn" {
  description = "The ARN of the OIDC Provider"
  value       = module.eks.oidc_provider_arn
}

output "rds_endpoint" {
  description = "The connection endpoint for the RDS instance"
  value       = module.db.db_instance_endpoint
  sensitive   = true
}

output "rds_port" {
  description = "The port the RDS instance is listening on"
  value       = module.db.db_instance_port
}

output "rds_security_group_id" {
  description = "Security group ID for RDS"
  value       = aws_security_group.rds.id
}

output "redis_endpoint" {
  description = "Redis primary endpoint"
  value       = module.redis.primary_endpoint
  sensitive   = true
}

output "redis_port" {
  description = "Redis port"
  value       = module.redis.port
}

output "redis_security_group_id" {
  description = "Security group ID for Redis"
  value       = aws_security_group.redis.id
}

output "s3_bucket_id" {
  description = "The name of the S3 bucket"
  value       = module.s3_bucket.s3_bucket_id
}

output "s3_bucket_arn" {
  description = "The ARN of the S3 bucket"
  value       = module.s3_bucket.s3_bucket_arn
}

output "route53_zone_id" {
  description = "The ID of the Route53 hosted zone"
  value       = aws_route53_zone.main.zone_id
}

output "route53_name_servers" {
  description = "The name servers for the Route53 hosted zone"
  value       = aws_route53_zone.main.name_servers
}

output "acm_certificate_arn" {
  description = "The ARN of the ACM certificate"
  value       = aws_acm_certificate.main.arn
}

# Kubernetes Config
output "kubectl_config" {
  description = "kubectl config as generated by the AWS CLI"
  value       = module.eks.kubeconfig
  sensitive   = true
}

# Additional Information
output "environment" {
  description = "The environment name"
  value       = var.environment
}

output "region" {
  description = "The AWS region"
  value       = var.aws_region
}

output "domain_name" {
  description = "The main domain name"
  value       = var.domain_name
}

# Cost Estimation (for reference)
output "estimated_monthly_costs" {
  description = "Estimated monthly costs for main components"
  value = {
    eks_cluster = "~$73.00 (control plane)"
    eks_nodes   = "~$140.16 (2 x t3.medium)"
    rds         = "~$50.96 (db.t3.medium)"
    redis       = "~$12.41 (cache.t3.micro)"
    total       = "~$276.53 (excluding data transfer and storage)"
  }
}

# Tags
output "common_tags" {
  description = "Tags applied to all resources"
  value       = var.tags
}

# Monitoring Information
output "cloudwatch_log_groups" {
  description = "CloudWatch Log Groups created"
  value = {
    eks     = "/aws/eks/${module.eks.cluster_id}/cluster"
    rds     = "/aws/rds/instance/${module.db.db_instance_id}"
    redis   = "/aws/elasticache/${module.redis.id}"
  }
}
