name: Frontend CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: nepse-simulator-app

      - name: Run lint
        run: npm run lint
        working-directory: nepse-simulator-app

      - name: Run tests
        run: npm test
        working-directory: nepse-simulator-app

      - name: Build app
        run: npm run build
        working-directory: nepse-simulator-app
